title: Ruan Pedro # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Desenvolvedor Java
  <br><br>
  Desenvolvedor Back-end, futuro ciêntista da computação e analista de segurança 
  <br><br>
  <a href="https://www.linkedin.com/in/ruan-p-186968191/">Meu perfil no Linkedin</a> 
   <a href="https://www.linkedin.com/in/ruan-p-186968191/">Meu perfil no Linkedin</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
